[env:esp32s3]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

; Serial monitor
monitor_speed = 115200

; Board has 16MB Flash and 8MB OPI PSRAM (N16R8)
board_build.flash_size        = 16MB
board_build.partitions        = default_16MB.csv
board_upload.flash_size       = 16MB
board_build.arduino.memory_type = qio_opi

; Libraries
lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit NeoPixel
    knolleary/PubSubClient